### ISSUE TITLE
Minting change going to Basecoin address instead of RingCT

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#339] opened 2019-01-28 02:02 UTC
Noticed only since 1.0.1.3 (on testnet).

In 1.0.1.2 I noticed that minting a zerocoin from mined basecoin sent the change to RingCT and later minted again and sent it back to RingCT. This seems to be the way it should work.

Since 1.0.1.3 suddenly I see that **some**, indeed **most** of the minting transactions have been returning change to a basecoin address.

I wondered if this was a display error so I checked the address (mrdDLrWnSUCUPZpES1ySQWyvhhykCgGjtA) in the Testnet Explorer, and I checked 
```getaddressinfo mrdDLrWnSUCUPZpES1ySQWyvhhykCgGjtA```
and then checked Coin Control and it says it is a basecoin address.

![screen shot 2019-01-28 at 12 41 40 pm](https://user-images.githubusercontent.com/46495592/51810123-1ae69c00-22fa-11e9-864a-a6bb489493dc.png)

![screen shot 2019-01-28 at 12 43 42 pm](https://user-images.githubusercontent.com/46495592/51810194-7ca70600-22fa-11e9-9b63-37aa1dced7b1.png)

Is this just a new thing, sending the change back to the basecoin address the mined the block?

I am raising this issue, just because I understand that basecoin transactions were supposed to be being phased out, and the previous version seemed to be not returning change to a basecoin address. 
¿¿ Maybe there is another (network) reason for the RingCT transactions not happening today ?? 
But maybe one of the changes in 1.0.1.3 inadvertently reduced the ability of RingCT transactions happening, or maybe that only could have happened on testnet due to no-one else doing transactions that could become part of the ring?

Here is one that went to basecoin 
```
2019-01-27T17:39:27Z CreateZerocoinMintTransaction: new mint  DeterministicMint:
2019-01-27T17:39:27Z CommitTransaction:
2019-01-27T17:39:27Z [default wallet] AddToWallet 5a0c8321220484f9f2cdc8e2937b1f5aa0c6831b389cdf6c3a7931c066fc431f  new
2019-01-27T17:39:27Z [default wallet] Relaying wtx 5a0c8321220484f9f2cdc8e2937b1f5aa0c6831b389cdf6c3a7931c066fc431f
2019-01-27T17:39:27Z CWallet::AutoZeromint() @ block 4309: successfully minted 10 Zerocoin. Current percentage of Zerocoin: 36.716065%
2019-01-27T17:39:27Z UpdateTip: new best=3d460ad8b589671cbd37a3832869587adfd4737733647855b1c37d587dd0a504 height=4309 version=0x20000000 log2_work=22.35512 tx=7469 date='2019-01-27T17:37:32Z' progress=0.316687 cache=0.7MiB(3615txo)
2019-01-27T17:39:27Z [default wallet] AddToWallet 5a0c8321220484f9f2cdc8e2937b1f5aa0c6831b389cdf6c3a7931c066fc431f  
2019-01-27T17:39:27Z ListMints: added 0 zerocoinmints from DB
2019-01-27T17:39:27Z ListMints: added 49 dzpiv from DB
2019-01-27T17:39:27Z ListMints: added 0 zerocoinmints from DB
2019-01-27T17:39:27Z ListMints: added 49 dzpiv from DB
```
Here is one that went to RingCT 
```
2019-01-27T17:46:29Z CreateZerocoinMintTransaction: new mint  DeterministicMint:
2019-01-27T17:46:29Z CommitTransaction:
2019-01-27T17:46:29Z [default wallet] AddToWallet 4e6c3454e6765586650068bcc75424c1abd4dbdba05f6887ed835aa9b2f1d71f  new
2019-01-27T17:46:29Z [default wallet] Relaying wtx 4e6c3454e6765586650068bcc75424c1abd4dbdba05f6887ed835aa9b2f1d71f
2019-01-27T17:46:29Z CWallet::AutoZeromint() @ block 4313: successfully minted 10 Zerocoin. Current percentage of Zerocoin: 38.071885%
```

**Comment by seanPhill** [comment] 2019-01-28 04:45
I've since noticed this also happening on mainnet from people's unsolicited screenshots to #support (for unrelated issues).

**Comment by presstab** [comment] 2019-02-10 01:47
Duplicate of #271

**Closed by presstab** 2019-02-10 01:47 UTC
Labels: Coin Type: Basecoin, Coin Type: Zerocoin, Component: Wallet, Dev Status: Help Wanted, Issue Type: Bug
