### ISSUE TITLE
Automint full balance if possible did not work

### ISSUE THREAD

**Issue by seanPhill** [Veil-Project/veil#415] opened 2019-02-28 15:38 UTC
Running on latest master (Feb 27 USA - Feb 28 Australian time) I withdrew basecoin from exchange, and tested the new Automint full balance if/whenever possible. About 374 Veil in basecoin.

I left it there for over 100 confirmations before changing the setting to automint hundreds.

The hundred autominted as expected (hoped).

I can only show the time between the basecoin deposit and the minting of the hundreds. Oh, except for the debug log, which for that whole time reported ```CWallet::AutoZeromint(): auto minting failed with error: Insufficient Basecoin Funds```

![screen shot 2019-03-01 at 2 36 21 am](https://user-images.githubusercontent.com/46495592/53578116-14826300-3bcb-11e9-93c6-b068c31a5615.png)

**Comment by StrontiumZ38** [comment] 2019-03-03 00:10
> Oh, except for the debug log, which for that whole time reported CWallet::AutoZeromint(): auto minting failed with error: Insufficient Basecoin Funds

I haven't looked into how it was coded, but I wonder if it was only looking for basecoin and you instead had CT. What were your balances at that point?

**Comment by furszy** [comment] 2019-03-03 00:31
Thanks for post it, the issue is the mint method and the subsequent mint tx creation. 
Need to polish those methods and create a pre-step for the value factorization.

**Comment by 4x13** [comment] 2019-03-05 09:41
Also, automint should use all coin types (basecoin, CT and then RingCT) .. :)

**Comment by blondfrogs** [comment] 2019-04-14 19:37
@furszy @veildev You are still assigned to this issue? Are you planning on fixing this or should be assign another dev?

**Comment by blondfrogs** [comment] 2019-04-17 16:54
Removing the assigned devs as they are not responding

**Closed** 2019-04-27 03:07 UTC
Labels: Coin Type: Zerocoin, Component: Wallet, Dev Status: Open PR
