### ISSUE TITLE
cs_main LOCK gets held by unknown process for a lengthy period of time.

### ISSUE THREAD

**Issue by mimirmim** [Veil-Project/veil#718] opened 2019-12-20 03:41 UTC
This is the cause of issues #717 and #716. `cs_main` is being held around 3 to 30 seconds at times, preventing many RPC / CLI calls as well as causing issues when sending responses to peers. Needs to be investigated what is holding the lock for such a long period of time. This particular issue doesn't exist in Bitcoin.

The expected behaviour is near-instant responses to RPC / CLI and P2P request methods.

Actual behaviour is that there is a long hold on the `cs_main` thread, causing issues across the software.

This is very trivial to reproduce this issue and exists across other projects forked from PIVX.

See #717 and #716 for more specific examples.

**Comment by sinetek** [comment] 2019-12-22 15:18
I want to look into this, but I can't seem to reproduce the slowness. ?

**Comment by CaveSpectre11** [comment] 2019-12-23 00:23
> I want to look into this, but I can't seem to reproduce the slowness. ?

I've been digging into it for about a week now.  I don't recall if Mimir confirmed it doesn't happen when you aren't staking; but I see the same problem with another coin.  The catch is that to really be able to see it, you need a lot of UTXOs staking, which is why I suspect the problem is in the way that scope is defined on locks...  I'm trying to confirm or disprove that having an empty block defining a lock...
```
{
  LOCK(cs_main);
 ...
}
```
May not actually release the lock.  If that theory is correct, then code like:

```
...CreateNewBlock...

    {
        LOCK(cs_main);
        //Do not pass in the chain tip, because it can change. Instead pass the blockindex directly from mapblockindex, which is const.
        auto pindexTip = chainActive.Tip();
        if (!pindexTip)
            return nullptr;
        auto hashBest = pindexTip->GetBlockHash();
        pindexPrev = mapBlockIndex.at(hashBest);
    }
...
        if (!gArgs.GetBoolArg("-disablewallet", DEFAULT_DISABLE_WALLET) && pwalletMain->CreateCoinStake(pindexPrev, pblock->nBits, txCoinS
```

Could very well be holding the lock while it calculates the hashes for each UTXO looking for a staking solution.

The reason I suspect there's something strange going on there is when I added some extra code to sync.h along with turning on `DEBUG_LOCKCONTENTION` and `DEBUG_LOCKORDER`.  What I found was:
```
2019-12-20T02:19:41Z Taking Lock: cs_vNodes [net.cpp:1457]
2019-12-20T02:19:41Z LOCKCONTENTION: cs_vNodes
2019-12-20T02:19:41Z Waiting for lock: cs_vNodes [net.cpp:2034]
2019-12-20T02:19:41Z Taking Lock: cs_vNodes [net.cpp:1166]
2019-12-20T02:19:41Z Taking Lock: cs_vNodes [net.cpp:1225]
2019-12-20T02:19:41Z Taking Lock: cs_vNodes [net.cpp:1257]
2019-12-20T02:19:41Z Taking Lock: cs_vNodes [net.cpp:2034]
```
If you chase those line numbers down; you will see it doesn't make sense that 2034 s waiting for the lock, and 1166, 1225 and 1257 gets it before... unless the lock is being held through a whole loop through the thread handler.

Trying to get a couple things added to the debug logic.
1. a "owns_lock" callable routine to see if we own the lock (to spot check in places the lock shouldn't be held.
2. a one back static map of all the locks; holding the last module and line number, so when a lock contention is hit, we can report who actually is holding the lock.
3. timing functionality to time how long we wait for the lock, allowing us to find the choke points and target them directly.

**Comment by mimirmim** [comment] 2019-12-23 10:19
Thanks for looking into this @CaveSpectre11

**Comment by mimirmim** [comment] 2020-01-02 09:46
This is solved in: https://github.com/Veil-Project/veil/pull/727

**Comment by sinetek** [comment] 2020-01-08 15:49
Can i close this?

**Comment by CaveSpectre11** [comment] 2020-01-08 17:26
> Can i close this?

No.  #727 is just one part of this.  There's more places that need to be addressed.  Also, 727 isn't merged into the codebase yet.  In general, an issue shouldn't be closed until the PR is complete (e.g. merged), and only if the PR fully addresses the issue.  In some cases, an issue can be closed when the PR is complete, even if it doesn't fully address the issue... if the remaining is better served as a separate issue.

In this case, however, this issue is still very much active... even with #727.  That PR is a major step in the right direction, but there's still more going on.

**Comment by seanPhill** [comment] 2023-05-21 19:38
[Chain][Performance] Rework orphan pruning #727 merge addressed this, and currently it is no longer "very much active", so I have had to remove the tags saying that there is current work in progress, and that it is an open PR.

If anyone wants to follow up any of this work they are welcome, but the issue has been addressed.

(Cleaning up)

**Closed by seanPhill** 2023-05-21 19:38 UTC
Labels: Priority: 3 - High, Component: RPC, Component: Core App, Component: Network
