### ISSUE TITLE
getbalance only shows basecoin balance

### ISSUE THREAD

**Issue by CryptoMaximalist** [Veil-Project/veil#474] opened 2019-04-04 02:18 UTC
The getbalance command only shows the spendable basecoin balance
Veil v1.0.2

**Comment by seanPhill** [comment] 2019-04-05 23:44
Should we make it an alias for getbalances or would you want this to be a grand total?

**Comment by CryptoMaximalist** [comment] 2019-04-06 01:47
I assume a grand total is the intention

**Comment by blondfrogs** [comment] 2019-04-11 23:43
Closing as this rpc call is working as intended. A new rpc call will be created to get the full balance of the wallet.

**Closed by blondfrogs** 2019-04-11 23:43 UTC
Labels: Component: Wallet, Dev Status: Help Wanted, Issue Type: Bug

**Comment by seanPhill** [comment] 2019-04-12 00:59
I can accept that, as having a standard getbalance call that reveals zero (basecoin) balance is a bit of a veil over a possibly high value account, that might help it escape the attention of hackers. :)

**Comment by MatWaller** [comment] 2019-05-07 08:23
#574 How about that? @seanPhill
