### ISSUE TITLE
Display warning on spend

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#171] opened 2019-01-04 00:29 UTC
Spending Zerocoins can result in a non-responsive period from the wallet that can be quite significant. Users have reported this as a crash/freeze. A warning on spend (mouseover for instance) that sending Zerocoins can leave the wallet unresponsive as it computes would alleviate this problem.

**Comment by presstab** [comment] 2019-02-11 22:21
Duplicate of #272 , which was created after this, but has more conversation, so closing this one.

**Closed by presstab** 2019-02-11 22:21 UTC
Labels: Coin Type: Zerocoin, Component: GUI, Dev Status: In Progress, Issue Type: Missing Functionality
