### ISSUE TITLE
Manual minting shows "insufficient funds" (testnet)

### ISSUE THREAD

**Issue by MisterKangaroo** [Veil-Project/veil#287] opened 2019-01-13 02:41 UTC
When manually minting zerocoins it shows a balance thats high enough to mint, but when clicking mint it shows a error message "Failed to add ringctinputs: ringctwallet Insufficient funds." and doesnt mint.
See screenshots below:
![insufficient funds2](https://user-images.githubusercontent.com/43561981/51080946-ff1dac00-16e4-11e9-9662-1e1d2973d667.PNG)
![insufficient funds](https://user-images.githubusercontent.com/43561981/51080947-004ed900-16e5-11e9-9f79-5d4f13bc9d44.PNG)

Windows 10 x64
Wallet version 1.0.0.9

**Comment by MisterKangaroo** [comment] 2019-01-13 04:43
perhaps some correlation: ringctwallet Not enough anon outputs exist, last: 9, required: 22. (code -4

**Comment by presstab** [comment] 2019-01-13 08:06
It is the anon outputs problem. This should not happend much unless on testnet.

**Comment by hoidsflute** [comment] 2019-01-16 19:59
I've found that waiting a few minutes for the newly minted coins to confirm resolves the issue temporarily.  Then I get the same error (failed to add ringctinputs) after minting 3-5 times.

**Comment by veilMaDOS** [comment] 2019-02-06 21:34
I am having this issue on the 1.0.1.4 wallet trying to mint 1000 CT (there is an extra 10 CT balance to account for fees) from either GUI or the console.

**Comment by seanPhill** [comment] 2019-04-02 03:27
This just happened to me on mainnet, when trying to `mintzerocoin 100` from RingCT, but I _had only just moved_ the funds into RingCT from CT. (And they had only just confirmed to spendable.)
```
./veil-cli mintzerocoin 100
error code: -4
error message:
Error: Failed to create transaction: Failed to add ringctinputs: 
```
**I waited a few more minutes and tried it again and it minted fine.**

**Comment by CaveSpectre11** [comment] 2020-07-02 17:08
There are changes made that improve the logging to the user; some more improvements are needed as well but this issue isn't an issue, not enough transactions on the chain to allow for the proper masking is expected behavior; as is the inability to mint from immature transactions.  Likewise if you have too many TXOs it won't be able to create the minting transaction (this limitation has been increased in the next release).

Closing this since it's overcome by a lot of events.

**Closed by CaveSpectre11** 2020-07-02 17:08 UTC
Labels: Coin Type: RingCT, Component: Wallet, Issue Type: Bug, Priority: 3 - High
