### ISSUE TITLE
1.0.3 cannot complete sync, shutsdown! (Win64)

### ISSUE THREAD

**Issue by spsbyter** [Veil-Project/veil#551] opened 2019-04-29 13:12 UTC
1.0.2 worked fine.
win64 release od 1.0.3 was unzipped to new folder, old wallet and chain data delete, and 
 new veil-qt executed - started sync, but finally got shutdown... started few more times (sometimes, it shows splashscreen and shutdowns immediately, before showing final wallet GUI, sometimes shows GUI, starts resync and after few hours shuts down!

until now, I tried 4-5x, cannot complete sync and get my 1.0.3 wallet working

last pieces of debug.log

2019-04-29T13:10:14Z UpdateTip: new best=e2595740638cd8600a7396eddeb9b61e64a92deca6e8313045ca23696e8677d4 height=102989 type=PoW version=0x20000000 tx=305414 date='2019-03-17T09:06:55Z' cache=0.0MiB(19txo)
2019-04-29T13:10:15Z ConnectBlock: Duplicate anon-output 02f4167e7c0952370aed4c4d6742dcb9268c89f283c55b79b5de621fe1376e4b69, index 7048, above last index 7047.
2019-04-29T13:10:15Z Attempting to repair anon index.
2019-04-29T13:10:15Z RollBackRCTIndex: Last valid 7047, expect to erase 7048, num ki 0
2019-04-29T13:10:15Z RollBackRCTIndex: Removed up to 7050
2019-04-29T13:10:15Z ERROR: ConnectTip(): ConnectBlock 77961d3b680bcf3b91815f285c647794a7d49140adba4490303ac063d1aac44f failed
2019-04-29T13:10:15Z Failed to connect best block ( (code 0))
2019-04-29T13:10:15Z GUI: Platform customization: "windows"
2019-04-29T13:10:15Z ThreadStakeMiner() start
2019-04-29T13:10:15Z ThreadStakeMiner exiting
2019-04-29T13:10:15Z ThreadStaging exiting
2019-04-29T13:10:15Z GUI: PaymentServer::LoadRootCAs: Loaded  49  root certificates
2019-04-29T13:10:15Z txindex is enabled at height 102989
2019-04-29T13:10:15Z txindex thread exit
2019-04-29T13:10:15Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_btnCopyAddress_clicked()
2019-04-29T13:10:15Z GUI: QMetaObject::connectSlotsByName: No matching signal for on_addressBookButton_clicked()
2019-04-29T13:10:15Z ThreadStaging exiting
2019-04-29T13:10:15Z tor: Thread interrupt
2019-04-29T13:10:15Z Shutdown: In progress...
2019-04-29T13:10:15Z torcontrol thread exit
2019-04-29T13:10:15Z addcon thread exit
2019-04-29T13:10:15Z dnsseed thread exit
2019-04-29T13:10:15Z net thread exit
2019-04-29T13:10:15Z msghand thread exit
2019-04-29T13:10:15Z opencon thread exit
2019-04-29T13:10:16Z scheduler thread interrupt
2019-04-29T13:10:16Z Dump Precomputes: 0s to dump
2019-04-29T13:10:16Z Shutdown: done

**Comment by spsbyter** [comment] 2019-04-29 17:18
tried again from scratch. removed all previous wallet data... sync for few hours... again shutdown...

**Comment by presstab** [comment] 2019-04-29 18:14
When you tried to resync from scratch what block did it get to?

**Comment by spsbyter** [comment] 2019-04-29 18:30
Not 100% sure, deleted log... ConnectBlock 3494732d196280247c924bc7fa50372af3d01d2e2a57a0d9cc3b8ace407940dd failed?

Will wait for this to end (started again, now on 17-03-2019 block sync...)...

**Comment by Strunczez** [comment] 2019-04-30 09:46
Same here, syncing 5th time from scrath. Somtimes wallet hangs immediately after starting exe, sometimes after one hour. Somtimes it show application stopped working message, sometimes it quits instantly without any message.

**Comment by FishMeat** [comment] 2019-05-01 15:55
me too win7

**Comment by spsbyter** [comment] 2019-05-02 09:13
Any solution?

**Comment by Veil-Grumpy** [comment] 2019-05-02 09:29
Please provide more information about your operating system details.

**Comment by spsbyter** [comment] 2019-05-02 09:34
Win10 64bit...

**Comment by Veil-Grumpy** [comment] 2019-05-02 09:39
Here is the fix:

Download this snapshot:
https://veil.tools/20190502-veil-daily-167277.zip

Close wallet, delete everything besides wallet.dat, wallets, backups, veil.conf
DONT IMPORT SNAPSHOT YET
Start wallet and let it find peers and catch up some blocks

Close wallet and replace blockchain with snapshot and start wallet

Some people might not have wallets folder or veil.conf, don’t worry about this.

**Comment by spsbyter** [comment] 2019-05-02 09:45
Hhih. 8GB... I need to prepare my SSD :-) Will let you know after trying it

**Comment by boxalex** [comment] 2019-05-02 09:48
Same here, Shuts down while syncing.
First time it happened i had it running for nearly 2 days on a top notch PC with a 1-3% progress per hour.
Last night when i went to sleep and left the PC syncing it was at about 88%, when i woke up, no Veil wallet online, no syncing, no nothing. Had to begin from 0% again. 
2nd attempt it just closed after and vanished after 1-2 minutes after syncing begin.
3rd attempt at least it continued from the last exit, as it was only about 1-2 mintues after about 1%.

Configuration: Veil Win64 .exe version, Win 10 64bit, I-7 8700k cpu, 64 GB RAM, at setup changed folder path to have it on F:/ instead of C:/, more than enough free space of course. No idea what other info could be usefull for you....

**Comment by Veil-Grumpy** [comment] 2019-05-02 09:59
Please do my suggestion I did post above.
Works 100%

Wallet will automatically rescan and It might take some time to complete after importing snapshot but just let it run! Don’t close it while rescan is running!

**Comment by boxalex** [comment] 2019-05-02 11:46
ok, got it to working. But i get a warning at the top of the wallet:
"Warning. Unknown new rules activated (versionbit 2)"
Normal?

**Comment by Veil-Grumpy** [comment] 2019-05-02 12:03
This message should disappear soon, don’t worry about that message. We all have it at the moment

**Comment by spsbyter** [comment] 2019-05-02 15:14
works for now

**Comment by presstab** [comment] 2019-05-02 15:58
I believe this is a duplicate of #547 . @blondfrogs has been working on a solution for this problem, believe we will have a more permanent one soon.

**Closed by presstab** 2019-05-02 15:58 UTC
