### ISSUE TITLE
Veil daemon stops without shutting down at block =105914

### ISSUE THREAD

**Issue by goodthebest** [Veil-Project/veil#562] opened 2019-05-02 15:27 UTC
Hey Devs,

Operating system: Ubuntu 18.06 and tested on Ubuntu 16.04 too

Veil version: v1.0.3.0

I've tried to sync veil chain on different machines and on all machines,veil daemon will stop at this height 105914 and when I restart the veil daemon it will re-sync from scratch and again will stop at 105914.

Daemon debug doesn't say anything much but syslog leaves some footprints for this issue. Please check these screenshots and suggest what is the cure!

## ubuntu Syslog

![image](https://user-images.githubusercontent.com/1715740/57086847-f68ec700-6d0f-11e9-9dac-e4a8ac9f8140.png)

## veil debug.log
![image](https://user-images.githubusercontent.com/1715740/57086973-305fcd80-6d10-11e9-8b0b-3d8fa801141d.png)

**Comment by presstab** [comment] 2019-05-02 15:56
Thanks for the logs. Believe this is a duplicate of #547

**Closed by presstab** 2019-05-02 15:56 UTC
