### ISSUE TITLE
Coin control unselect all - fatal error

### ISSUE THREAD

**Issue by StrontiumZ38** [Veil-Project/veil#813] opened 2020-07-31 17:35 UTC
Win64 1.0.4.8

Using the (un)select all button in Coin control resulted in a fatal error, forced shutdown of wallet application, and a subsequent corruption calling for snapshot.

**Comment by CaveSpectre11** [comment] 2020-07-31 17:48
Please test with the latest wallet; this is likely a duplicate of #660 or #661 and fixed with #757 

You can find the latest wallet here:
https://github.com/Veil-Project/veil/actions/runs/187835942

**Closed by CaveSpectre11** 2020-07-31 17:48 UTC
Labels: Tag: Duplicate

**Comment by StrontiumZ38** [comment] 2020-07-31 17:55
Cheers
